upstream backend {
    server django:8000;
    
}
server{
    listen 80;

    location /static {
        alias /static;
    }
    location / {
        proxy_pass http://django:8000;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
}

